nile-common: gpt-utils: Drop -Wno-unused-variable and address one warning.
hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp:750:17: error: unused variable 'ufs_dir_stat' [-Werror,-Wunused-variable]
    struct stat ufs_dir_stat;
                ^
hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp:973:13: error: unused variable 'r' [-Werror,-Wunused-variable]
        int r, fd;
            ^
hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp:973:16: error: unused variable 'fd' [-Werror,-Wunused-variable]
        int r, fd;
               ^
3 errors generated.

[ 22% 4/18] target  C++: libgptutils <= hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp
In file included from hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp:54:
system/core/libcutils/include_vndk/cutils/log.h:38:2: warning: "Deprecated: don't include cutils/log.h, use either android/log.h or log/log.h" [-W#warnings]
 ^
1 warning generated.

Test: lunch aosp_walleye-userdebug && m -j libgptutils
Change-Id: Ie3c33cc61fc62ac93ab0954a9e292b62cfcf9e03